version: '3'
services:
  db:
    image: mysql:8.1
    container_name: c1
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mkyong
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
